language: go
go:
- 1.11.x
- 1.12.x
- 1.13.x
- 1.14.x

before_install:
- export GO111MODULE=on
script:
- cd session && go test ${gobuild_args} ./... && cd ..
- cd marshal && go test ${gobuild_args} ./... && cd ..
- if [[ $TRAVIS_GO_VERSION = 1.14.x ]]; then gofmt -d .; fi
- if [[ $TRAVIS_GO_VERSION = 1.14.x ]]; then test -z $(gofmt -d .); fi
