name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
        - "1.11"
        - "1.12"
        - "1.13"
        - "1.14"
        - "1.15"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Test ./session
      run: cd session && go test ./...
    - name: Test ./marshal
      run: cd session && go test ./...
    - name: Check format
      run: |
        gofmt -d .
        test -z $(gofmt -d .)
      if: ${{ matrix.go == '1.14' }}
